### ISSUE TITLE
Redirect mismatch

### ISSUE THREAD

**Issue by Raudcu** [fspijkerman/dash-cognito-auth#18]
The problem I'm having is that de redirect_uri is an http uri, which generates for me a redirect mismatch because Cognito is expecting https. I didn't find any way to customize this. 

Thanks in advance!

**Comment by MauriceBrg** [comment]
For future readers, you can set the environment variable `OAUTHLIB_INSECURE_TRANSPORT` to `"1"` to allow for `http://` URIs within the app.

https://github.com/fspijkerman/dash-cognito-auth/blob/9e1af9fb7df660fc8e881c85e873eb5eab9fd157/example/app.py#L10

You also need to ensure the Cognito Settings allow the URLs with the `http://` prefix, but you should really only do this for (local) development.

https://github.com/fspijkerman/dash-cognito-auth/blob/9e1af9fb7df660fc8e881c85e873eb5eab9fd157/example/aws_resources.yaml#L51
