### ISSUE TITLE
Session problem

### ISSUE THREAD

**Issue by dopic** [fspijkerman/dash-cognito-auth#19]
Hi, I'm new to Dash, and I'm using dash-cognito-auth. My application uses Client Sessions (I don't have Flask-Session), and I log in and out normally. However, in some situations, if another user logs in after me (in another browser/workstation), my session starts to show the other person's user. As if their session replaces mine.

Any idea why this happens?

Thank you!

**Comment by MauriceBrg** [comment]
By "client sessions", are you referring to Cookie-Based sessions?

This is usually an indicator that you're storing data in global variables or something like that which persist over the lifecycle of multiple requests. Essentially something that circumvents the existing session management mechanisms of Flask / Dash.

IMO it's _very_ unlikely that this is something related to this library or the way Flask handles sessions (which this library builds on).

**Comment by dopic** [comment]
Thanks, Maurice. Yes, the app uses cookie-based sessions.
I'll look into the code based on your recommendation.
